// ════════════════════════════════════
  // JUDICIALES
  // Fuentes:
  //   · Total acuerdos mes activo (con honorarios) → INFORME_JUDICIAL_MAYO_2026.xlsx
  //     Solo existe dato de Mayo 2025 ($57.4M) y Mayo 2026 ($186.3M). Ene–Abr 2025 = S/D.
  //   · Total acuerdos (solo actor), pago mes, cuotas pendientes → ACUERDOS_LABORALES_2026.xlsx
  //   · "Total acuerdos — mes activo" = suma total del acuerdo (actor + honorarios) de los
  //     acuerdos cuya primera cuota vence en ese mes. Para Ene–Abr se usa la suma solo actor
  //     (honorarios no disponibles en ese archivo).
  //   · "Total pago — mes activo" = suma de TODAS las cuotas (de cualquier acuerdo) que
  //     vencen en ese mes.
  //   · "Cuotas pendientes" = cuotas con vto en meses futuros correspondientes a acuerdos
  //     iniciados en ese mes.
  // ════════════════════════════════════
  judiciales: {
    ene: {
      kpis: [
        { label:'Total acuerdos — mes activo', value:'$95.2M',  delta:{ dir:'neutral', text:'17 acuerdos · Ene 2026 (solo actor, sin honorarios)' } },
        { label:'Total acuerdos — año ant.',   value:'S/D',     delta:{ dir:'neutral', text:'Sin informe Ene 2025' } },
        { label:'Total pago — mes activo',     value:'$39.5M',  delta:{ dir:'neutral', text:'Cuotas con vto. Ene 2026' } },
        { label:'Cuotas pendientes',           value:'$55.7M',  delta:{ dir:'neutral', text:'Vto. Feb 2026 en adelante · acuerdos de Ene' } },
      ],
      charts: [
        { type:'bar', title:'Evolución acuerdos', sub:'Millones $ · total acuerdo por mes (actor)', data:[{x:'Ene',y:95.2},{x:'Feb',y:18.5},{x:'Mar',y:55.9},{x:'Abr',y:85.7},{x:'May',y:140.8}] },
        { type:'bar', title:'Evolución pagos mensuales', sub:'Millones $ · cuotas vencidas por mes', data:[{x:'Ene',y:39.5},{x:'Feb',y:46.2},{x:'Mar',y:67.3},{x:'Abr',y:84.4},{x:'May',y:121.9}] },
        { type:'donut', title:'Distribución por tipo (monto)', sub:'% del total · Ene 2026', center:'$95.2M', data:[
          {label:'Sabores',  value:63.2},
          {label:'Fábrica',  value:32.1},
          {label:'Extremas', value:2.3},
          {label:'Staff',    value:2.3},
        ]},
      ],
    },
    feb: {
      kpis: [
        { label:'Total acuerdos — mes activo', value:'$18.5M',  delta:{ dir:'down',    text:'4 acuerdos · Feb 2026 (solo actor, sin honorarios)' } },
        { label:'Total acuerdos — año ant.',   value:'S/D',     delta:{ dir:'neutral', text:'Sin informe Feb 2025' } },
        { label:'Total pago — mes activo',     value:'$46.2M',  delta:{ dir:'up',      text:'+$6.7M vs. mes ant.' } },
        { label:'Cuotas pendientes',           value:'$8.0M',   delta:{ dir:'down',    text:'Vto. Mar 2026 en adelante · acuerdos de Feb' } },
      ],
      charts: [
        { type:'bar', title:'Evolución acuerdos', sub:'Millones $ · total acuerdo por mes (actor)', data:[{x:'Ene',y:95.2},{x:'Feb',y:18.5},{x:'Mar',y:55.9},{x:'Abr',y:85.7},{x:'May',y:140.8}] },
        { type:'bar', title:'Evolución pagos mensuales', sub:'Millones $ · cuotas vencidas por mes', data:[{x:'Ene',y:39.5},{x:'Feb',y:46.2},{x:'Mar',y:67.3},{x:'Abr',y:84.4},{x:'May',y:121.9}] },
        { type:'donut', title:'Distribución por tipo (monto)', sub:'% del total · Feb 2026', center:'$18.5M', data:[
          {label:'Fábrica',  value:32.4},
          {label:'Staff',    value:24.3},
          {label:'Extremas', value:21.6},
          {label:'Sabores',  value:21.6},
        ]},
      ],
    },
    mar: {
      kpis: [
        { label:'Total acuerdos — mes activo', value:'$55.9M',  delta:{ dir:'up',      text:'21 acuerdos · Mar 2026 (solo actor, sin honorarios)' } },
        { label:'Total acuerdos — año ant.',   value:'S/D',     delta:{ dir:'neutral', text:'Sin informe Mar 2025' } },
        { label:'Total pago — mes activo',     value:'$67.3M',  delta:{ dir:'up',      text:'+$21.1M vs. mes ant.' } },
        { label:'Cuotas pendientes',           value:'$12.9M',  delta:{ dir:'neutral', text:'Vto. Abr 2026 en adelante · acuerdos de Mar' } },
      ],
      charts: [
        { type:'bar', title:'Evolución acuerdos', sub:'Millones $ · total acuerdo por mes (actor)', data:[{x:'Ene',y:95.2},{x:'Feb',y:18.5},{x:'Mar',y:55.9},{x:'Abr',y:85.7},{x:'May',y:140.8}] },
        { type:'bar', title:'Evolución pagos mensuales', sub:'Millones $ · cuotas vencidas por mes', data:[{x:'Ene',y:39.5},{x:'Feb',y:46.2},{x:'Mar',y:67.3},{x:'Abr',y:84.4},{x:'May',y:121.9}] },
        { type:'hbar', title:'Monto por razón social — mes activo', sub:'Millones $ · solo actor', data:[
          {x:'LA EMPANADERIA S.A',             y:11.30},
          {x:'CASTRO CINTIA NOEMI',            y:8.35},
          {x:'DICK AND MAC S.A',               y:8.00},
          {x:'MOSCARELLA CLAUDIO ARIEL',       y:4.00},
          {x:'CASUT FRIJON MATIAS EZEQUIEL',   y:4.00},
          {x:'SAYAGO MARCIO HUMBERTO NICOLAS', y:3.60},
          {x:'GONZALEZ MIGUEL ANGEL',          y:3.50},
          {x:'GREISSI RUANO ROJAS',            y:2.50},
          {x:'ANA BELEN GONZALEZ',             y:2.50},
          {x:'MENDOZA NICOLAS MATIAS',         y:2.00},
        ]},
        { type:'donut', title:'Distribución por tipo (monto)', sub:'% del total · Mar 2026', center:'$55.9M', data:[
          {label:'Extremas', value:34.9},
          {label:'Sabores',  value:31.2},
          {label:'Fábrica',  value:24.1},
          {label:'Staff',    value:9.8},
        ]},
      ],
    },
    abr: {
      kpis: [
        { label:'Total acuerdos — mes activo', value:'$85.7M',  delta:{ dir:'up',      text:'30 acuerdos · Abr 2026 (solo actor, sin honorarios)' } },
        { label:'Total acuerdos — año ant.',   value:'S/D',     delta:{ dir:'neutral', text:'Sin informe Abr 2025' } },
        { label:'Total pago — mes activo',     value:'$84.4M',  delta:{ dir:'up',      text:'+$17.1M vs. mes ant.' } },
        { label:'Cuotas pendientes',           value:'$34.1M',  delta:{ dir:'up',      text:'Vto. May 2026 en adelante · acuerdos de Abr' } },
      ],
      charts: [
        { type:'bar', title:'Evolución acuerdos', sub:'Millones $ · total acuerdo por mes (actor)', data:[{x:'Ene',y:95.2},{x:'Feb',y:18.5},{x:'Mar',y:55.9},{x:'Abr',y:85.7},{x:'May',y:140.8}] },
        { type:'bar', title:'Evolución pagos mensuales', sub:'Millones $ · cuotas vencidas por mes', data:[{x:'Ene',y:39.5},{x:'Feb',y:46.2},{x:'Mar',y:67.3},{x:'Abr',y:84.4},{x:'May',y:121.9}] },
        { type:'hbar', title:'Monto por razón social — mes activo', sub:'Millones $ · solo actor', data:[
          {x:'PISANIELLO IVO',                  y:15.20},
          {x:'LA EMPANADERIA S.A',              y:14.50},
          {x:'CASUT FRIJON MATIAS EZEQUIEL',    y:11.60},
          {x:'SAYAGO MARCIO HUMBERTO NICOLAS',  y:8.00},
          {x:'CASTRO CINTIA NOEMI',             y:6.00},
          {x:'BOLLOS Y RELLENOS S.A',           y:5.00},
          {x:'SORIA FRANCISCO ADRIAN',          y:5.00},
          {x:'RIOS BRUNO',                      y:4.00},
          {x:'RUANO ROJAS GREISSI',             y:3.80},
          {x:'COMACHI VALERIA SABRINA',         y:3.00},
        ]},
        { type:'donut', title:'Distribución por tipo (monto)', sub:'% del total · Abr 2026', center:'$85.7M', data:[
          {label:'Sabores',  value:56.9},
          {label:'Fábrica',  value:22.8},
          {label:'Extremas', value:10.5},
          {label:'Staff',    value:9.8},
        ]},
      ],
      details: [{
        key:'detalle-abr', title:'Detalle acuerdos — Abr 2026', iconEmoji:'⚖️', accent:'purple', type:'table',
        topChips:[{label:'Sabores',value:'56.9%',tone:'green'},{label:'Fábrica',value:'22.8%',tone:'blue'},{label:'Extremas',value:'10.5%',tone:'purple'},{label:'Staff',value:'9.8%',tone:'amber'}],
        columns:[{key:'razon',label:'RAZÓN SOCIAL'},{key:'unidad',label:'LOCAL / FÁBRICA'},{key:'tipo',label:'TIPO',badge:true},{key:'actor',label:'ACTOR',align:'right'},{key:'total',label:'TOTAL (c/hon.)',align:'right',strong:true}],
        rows:[
          {razon:'BOLLOS Y RELLENOS S.A',           unidad:'MANTENIMIENTO FABRICA',    tipo:'Fábrica',  actor:'$5.000.000',  total:'S/D'},
          {razon:'CASTRO CINTIA NOEMI',             unidad:'SABORES ENTRE RIOS',       tipo:'Sabores',  actor:'$4.000.000',  total:'S/D'},
          {razon:'CASTRO CINTIA NOEMI',             unidad:'EXTREMAS SAN FERNANDO',    tipo:'Extremas', actor:'$1.000.000',  total:'S/D'},
          {razon:'CASUT FRIJON MATIAS EZEQUIEL',    unidad:'SABORES LANUS',            tipo:'Sabores',  actor:'$3.600.000',  total:'S/D'},
          {razon:'CASUT FRIJON MATIAS EZEQUIEL',    unidad:'HURLINGHAM SABORES II',    tipo:'Sabores',  actor:'$8.000.000',  total:'S/D'},
          {razon:'CASUT FRIJON MATIAS EZEQUIEL',    unidad:'EXTREMAS LUJAN',           tipo:'Extremas', actor:'$2.018.000',  total:'S/D'},
          {razon:'COMACHI VALERIA SABRINA',         unidad:'SABORES BALLESTER II',     tipo:'Sabores',  actor:'$3.000.000',  total:'S/D'},
          {razon:'DIEGO FERNANDO ARRIAGA DONAYRE',  unidad:'SABORES SAN FERNANDO',     tipo:'Sabores',  actor:'$2.000.000',  total:'S/D'},
          {razon:'ESCOBAR FACUNDO ARENA',           unidad:'FABRICA SAN MARTIN',       tipo:'Fábrica',  actor:'$8.800.000',  total:'S/D'},
          {razon:'ESMAY GONZALEZ RODRIGO',          unidad:'EXTREMAS SAN ISIDRO',      tipo:'Extremas', actor:'$2.000.000',  total:'S/D'},
          {razon:'FERNANDEZ GASTON KEVIN',          unidad:'EXTREMAS SAN FERNANDO',    tipo:'Extremas', actor:'$2.500.000',  total:'S/D'},
          {razon:'FERNANDEZ MOROSINI',              unidad:'SABORES PALOMAR',          tipo:'Sabores',  actor:'$4.000.000',  total:'S/D'},
          {razon:'FLORENCIA ROSALIA MARTIN',        unidad:'HURLINGHAM SABORES II',    tipo:'Sabores',  actor:'$8.000.000',  total:'S/D'},
          {razon:'GONZALEZ KEVIN NAHUEL',           unidad:'FABRICA SAN MARTIN',       tipo:'Fábrica',  actor:'$1.700.000',  total:'S/D'},
          {razon:'GONZALEZ LUCILA',                 unidad:'EXTREMAS LUJAN',           tipo:'Extremas', actor:'$2.018.000',  total:'S/D'},
          {razon:'LA EMPANADERIA S.A',              unidad:'FABRICA SAN MARTIN',       tipo:'Fábrica',  actor:'$2.900.000',  total:'S/D'},
          {razon:'MARIA ANGELES PALAVECINO',        unidad:'SABORES TIGRE',            tipo:'Sabores',  actor:'$1.650.000',  total:'S/D'},
          {razon:'MARIA ELIZA CHAZARRETA',          unidad:'SABORES HURLINGHAM II',    tipo:'Sabores',  actor:'$4.000.000',  total:'S/D'},
          {razon:'MOYANO MALENA',                   unidad:'FABRICA SAN MARTIN',       tipo:'Fábrica',  actor:'$2.200.000',  total:'S/D'},
          {razon:'ORRREGO CINTIA BEATRIZ',          unidad:'SABORES BALLESTER II',     tipo:'Sabores',  actor:'$3.000.000',  total:'S/D'},
          {razon:'OTADUY MARTINEZ SOL NAHIR',       unidad:'EXTREMAS SAN FERNANDO',    tipo:'Extremas', actor:'$2.000.000',  total:'S/D'},
          {razon:'PALMA NOBLE JUAN IGNACIO',        unidad:'SABORES FLORES II',        tipo:'Sabores',  actor:'$1.500.000',  total:'S/D'},
          {razon:'PISANIELLO IVO',                  unidad:'MANTENIMIENTO LOCALES',    tipo:'Sabores',  actor:'$12.000.000', total:'S/D'},
          {razon:'PISANIELLO IVO',                  unidad:'EXTREMAS SAN ISIDRO',      tipo:'Extremas', actor:'$2.000.000',  total:'S/D'},
          {razon:'RAMIREZ MARIA CELESTE',           unidad:'SABORES ENTRE RIOS',       tipo:'Sabores',  actor:'$4.000.000',  total:'S/D'},
          {razon:'RIOS BRUNO',                      unidad:'SABORES CORRIENTES I',     tipo:'Sabores',  actor:'$10.000.000', total:'S/D'},
          {razon:'RUANO ROJAS GREISSI',             unidad:'EXTREMAS SAN FERNANDO',    tipo:'Extremas', actor:'$1.800.000',  total:'S/D'},
          {razon:'SATAS LOURDES',                   unidad:'SABORES MDQ I',            tipo:'Sabores',  actor:'$1.157.360',  total:'S/D'},
          {razon:'SAYAGO MARCIO HUMBERTO NICOLAS',  unidad:'SABORES SAN FERNANDO',     tipo:'Sabores',  actor:'$2.000.000',  total:'S/D'},
          {razon:'SORIA FRANCISCO ADRIAN',          unidad:'SABORES BOULOGNE',         tipo:'Sabores',  actor:'$5.000.000',  total:'S/D'},
        ],
        totalRow:{ label:'TOTAL ABR 2026 (actor)', value:'$85.657.360' },
      }],
    },
    may: {
      kpis: [
        { label:'Total acuerdos — mes activo', value:'$186.3M', delta:{ dir:'up',      text:'38 acuerdos · May 2026 (c/honorarios · fuente informe judicial)' } },
        { label:'Total acuerdos — año ant.',   value:'$57.4M',  delta:{ dir:'neutral', text:'+224.6% interanual · 21 acuerdos May 2025' } },
        { label:'Total pago — mes activo',     value:'$121.9M', delta:{ dir:'up',      text:'+$37.5M vs. mes ant. · cuotas vencidas May 2026' } },
        { label:'Cuotas pendientes',           value:'$46.7M',  delta:{ dir:'up',      text:'Vto. Jun 2026 en adelante · acuerdos iniciados en May' } },
      ],
      charts: [
        { type:'bar', title:'Evolución acuerdos', sub:'Millones $ · total acuerdo por mes (actor)', data:[{x:'Ene',y:95.2},{x:'Feb',y:18.5},{x:'Mar',y:55.9},{x:'Abr',y:85.7},{x:'May',y:140.8}] },
        { type:'bar', title:'Evolución pagos mensuales', sub:'Millones $ · cuotas vencidas por mes', data:[{x:'Ene',y:39.5},{x:'Feb',y:46.2},{x:'Mar',y:67.3},{x:'Abr',y:84.4},{x:'May',y:121.9}] },
        { type:'hbar', title:'Monto por razón social — mes activo', sub:'Millones $ · c/honorarios', data:[
          {x:'CHUSPITA MARTIN DANIEL',            y:38.18},
          {x:'LA EMPANADERIA',                    y:29.76},
          {x:'GONZALEZ MIGUEL ANGEL',             y:14.13},
          {x:'BOLLOS Y RELLENOS',                 y:13.00},
          {x:'IVO PISANIELLO',                    y:11.93},
          {x:'BRUNO RIOS',                        y:11.45},
          {x:'VILLA MARIANO DAVID',               y:11.37},
          {x:'CASTRO CINTIA NOEMI',               y:11.13},
          {x:'RUANO ROJAS GREISSI',               y:9.93},
          {x:'COMACHI VALERIA SABRINA',           y:7.33},
          {x:'SAYAGO MARCIO HUMBERTO NICOLAS',    y:7.20},
          {x:'VICTORICA ANA MACARENA',            y:4.93},
          {x:'TABEIRA DELGADO GABRIEL',           y:4.48},
          {x:'CERTALDO SA',                       y:3.76},
          {x:'VICTORICA BARBARA ALEJANDRA',       y:3.27},
          {x:'SORIA ADRIAN FRANCISCO',            y:2.60},
          {x:'CLAUDIO ARIEL MOSCARELLA',          y:1.86},
        ]},
        { type:'donut', title:'Distribución por tipo (monto)', sub:'% del total · May 2026', center:'$186.3M', data:[
          {label:'Sabores',  value:57.5},
          {label:'Fábrica',  value:25.0},
          {label:'Extremas', value:17.5},
        ]},
      ],
      details: [{
        key:'detalle-may', title:'Detalle acuerdos — May 2026', iconEmoji:'⚖️', accent:'purple', type:'table',
        topChips:[{label:'Sabores',value:'57.5%',tone:'green'},{label:'Fábrica',value:'25.0%',tone:'blue'},{label:'Extremas',value:'17.5%',tone:'purple'}],
        columns:[{key:'razon',label:'RAZÓN SOCIAL'},{key:'unidad',label:'LOCAL / FÁBRICA'},{key:'tipo',label:'TIPO',badge:true},{key:'actor',label:'ACTOR',align:'right'},{key:'total',label:'TOTAL (c/hon.)',align:'right',strong:true}],
        rows:[
          {razon:'BOLLOS Y RELLENOS',              unidad:'FABRICA PROCESADORA',       tipo:'Fábrica',  actor:'$2.000.000',   total:'$2.531.670'},
          {razon:'BOLLOS Y RELLENOS',              unidad:'FABRICA SAN MIGUEL',        tipo:'Fábrica',  actor:'$6.000.000',   total:'$7.331.670'},
          {razon:'BOLLOS Y RELLENOS',              unidad:'FABRICA MEDIALUNAS',        tipo:'Fábrica',  actor:'$2.500.000',   total:'$3.133.650'},
          {razon:'BRUNO RIOS',                     unidad:'SABORES ROSARIO II',        tipo:'Sabores',  actor:'$3.200.000',   total:'$4.808.793'},
          {razon:'BRUNO RIOS',                     unidad:'SABORES ROSARIO I',         tipo:'Sabores',  actor:'$1.200.000',   total:'$1.680.960'},
          {razon:'BRUNO RIOS',                     unidad:'SABORES HURLINGHAM II',     tipo:'Sabores',  actor:'$4.000.000',   total:'$4.961.720'},
          {razon:'CASTRO CINTIA NOEMI',            unidad:'SABORES PACHECO I',         tipo:'Sabores',  actor:'$2.500.000',   total:'$3.083.500'},
          {razon:'CASTRO CINTIA NOEMI',            unidad:'SABORES PACHECO I',         tipo:'Sabores',  actor:'$3.500.000',   total:'$4.283.500'},
          {razon:'CASTRO CINTIA NOEMI',            unidad:'SABORES LAVALLE I',         tipo:'Sabores',  actor:'$3.000.000',   total:'$3.761.717'},
          {razon:'CERTALDO SA',                    unidad:'FABRICA TAPAS II',          tipo:'Fábrica',  actor:'$3.000.000',   total:'$3.759.321'},
          {razon:'CHUSPITA MARTIN DANIEL',         unidad:'SABORES MDQ 3',             tipo:'Sabores',  actor:'$22.500.000',  total:'$29.446.000'},
          {razon:'CHUSPITA MARTIN DANIEL',         unidad:'SABORES MDQ 4',             tipo:'Sabores',  actor:'$7.000.000',   total:'$8.732.500'},
          {razon:'CLAUDIO ARIEL MOSCARELLA',       unidad:'EXTREMAS LANUS II',         tipo:'Extremas', actor:'$1.500.000',   total:'$1.856.670'},
          {razon:'COMACHI VALERIA SABRINA',        unidad:'SABORES SAN MARTIN',        tipo:'Sabores',  actor:'$6.000.000',   total:'$7.333.650'},
          {razon:'GONZALEZ MIGUEL ANGEL',          unidad:'EXTREMAS MUNRO',            tipo:'Extremas', actor:'$2.000.000',   total:'$2.523.650'},
          {razon:'GONZALEZ MIGUEL ANGEL',          unidad:'EXTREMAS MUNRO',            tipo:'Extremas', actor:'$2.500.000',   total:'$3.133.650'},
          {razon:'GONZALEZ MIGUEL ANGEL',          unidad:'EXTREMAS MUNRO',            tipo:'Extremas', actor:'$2.000.000',   total:'$2.559.321'},
          {razon:'GONZALEZ MIGUEL ANGEL',          unidad:'EXTREMAS CABALLITO',        tipo:'Extremas', actor:'$1.200.000',   total:'$1.576.071'},
          {razon:'GONZALEZ MIGUEL ANGEL',          unidad:'SABORES DEL VISO',          tipo:'Sabores',  actor:'$3.500.000',   total:'$4.333.650'},
          {razon:'IVO PISANIELLO',                 unidad:'SABORES ZARATE',            tipo:'Sabores',  actor:'$2.500.000',   total:'$3.080.860'},
          {razon:'IVO PISANIELLO',                 unidad:'SABORES ZARATE',            tipo:'Sabores',  actor:'$800.000',     total:'$1.040.860'},
          {razon:'IVO PISANIELLO',                 unidad:'EXTREMAS BOULOGNE',         tipo:'Extremas', actor:'$2.000.000',   total:'$2.531.670'},
          {razon:'IVO PISANIELLO',                 unidad:'EXTREMAS OLIVOS',           tipo:'Extremas', actor:'$4.000.000',   total:'$5.280.960'},
          {razon:'LA EMPANADERIA',                 unidad:'FABRICA SAN MARTIN',        tipo:'Fábrica',  actor:'$3.200.000',   total:'$4.293.650'},
          {razon:'LA EMPANADERIA',                 unidad:'FABRICA SAN MARTIN',        tipo:'Fábrica',  actor:'$18.000.000',  total:'$21.733.000'},
          {razon:'LA EMPANADERIA',                 unidad:'FABRICA SAN MARTIN',        tipo:'Fábrica',  actor:'$3.000.000',   total:'$3.731.670'},
          {razon:'RUANO ROJAS GREISSI',            unidad:'EXTREMAS RODRIGUEZ',        tipo:'Extremas', actor:'$2.500.000',   total:'$3.159.320'},
          {razon:'RUANO ROJAS GREISSI',            unidad:'EXTREMAS SAN FERNANDO',     tipo:'Extremas', actor:'$2.000.000',   total:'$2.483.532'},
          {razon:'RUANO ROJAS GREISSI',            unidad:'EXTREMAS SAN FERNANDO',     tipo:'Extremas', actor:'$3.500.000',   total:'$4.283.531'},
          {razon:'SAYAGO MARCIO HUMBERTO NICOLAS', unidad:'SABORES BOEDO',             tipo:'Sabores',  actor:'$6.000.000',   total:'$7.200.000'},
          {razon:'SORIA ADRIAN FRANCISCO',         unidad:'SABORES SAN FERNANDO',      tipo:'Sabores',  actor:'$1.200.000',   total:'$1.541.074'},
          {razon:'SORIA ADRIAN FRANCISCO',         unidad:'SABORES SAN FERNANDO',      tipo:'Sabores',  actor:'$800.000',     total:'$1.061.073'},
          {razon:'TABEIRA DELGADO GABRIEL',        unidad:'SABORES CORRIENTES II',     tipo:'Sabores',  actor:'$3.500.000',   total:'$4.480.650'},
          {razon:'VICTORICA ANA MACARENA',         unidad:'SABORES BERAZATEGUI II',    tipo:'Sabores',  actor:'$4.000.000',   total:'$4.931.670'},
          {razon:'VICTORICA BARBARA ALEJANDRA',    unidad:'EXTREMAS FLORES',           tipo:'Extremas', actor:'$2.500.000',   total:'$3.266.717'},
          {razon:'VILLA MARIANO DAVID',            unidad:'SABORES PACHECO II',        tipo:'Sabores',  actor:'$3.500.000',   total:'$4.361.741'},
          {razon:'VILLA MARIANO DAVID',            unidad:'SABORES MORENO',            tipo:'Sabores',  actor:'$2.500.000',   total:'$3.133.650'},
          {razon:'VILLA MARIANO DAVID',            unidad:'SABORES POLVORINES',        tipo:'Sabores',  actor:'$3.000.000',   total:'$3.870.300'},
        ],
        totalRow:{ label:'TOTAL MAY 2026 (c/honorarios)', value:'$186.297.591' },
      }],
    },
  },
