// Mock data for each sector — ACTUALIZADO CON DATOS REALES (mayo 2026)
window.MONTHS = [
  { key: 'ene', short: 'ENE', year: 2026 },
  { key: 'feb', short: 'FEB', year: 2026 },
  { key: 'mar', short: 'MAR', year: 2026 },
  { key: 'abr', short: 'ABR', year: 2026 },
];

const acc = {
  blue:   { '--accent': 'linear-gradient(90deg,#6FA0F2,#8DB3F7)', '--accent-color': '#4F86E8', '--accent-soft': '#EAF2FE', '--accent-glow': 'rgba(111,160,242,0.26)' },
  cyan:   { '--accent': 'linear-gradient(90deg,#6CC8DC,#8DB3F7)', '--accent-color': '#2F9CB5', '--accent-soft': '#E3F4F8', '--accent-glow': 'rgba(108,200,220,0.28)' },
  purple: { '--accent': 'linear-gradient(90deg,#A8A4F0,#C9B6F2)', '--accent-color': '#6E68C9', '--accent-soft': '#EFEDFB', '--accent-glow': 'rgba(168,164,240,0.28)' },
  amber:  { '--accent': 'linear-gradient(90deg,#E8B86A,#F0CE8E)', '--accent-color': '#B68235', '--accent-soft': '#FBF1DF', '--accent-glow': 'rgba(232,184,106,0.30)' },
  green:  { '--accent': 'linear-gradient(90deg,#5EBA8A,#9AD4B2)', '--accent-color': '#2C7E51', '--accent-soft': '#E4F2EA', '--accent-glow': 'rgba(94,186,138,0.28)' },
  red:    { '--accent': 'linear-gradient(90deg,#E26666,#F09898)', '--accent-color': '#A8453C', '--accent-soft': '#F8E5E3', '--accent-glow': 'rgba(226,102,102,0.26)' },
};
window.ACCENTS = acc;

window.SECTORS = [
  {
    id: 'empresa',
    group: 'UNIDADES',
    name: 'Empresa Total',
    sub: 'Visión consolidada · todas las razones sociales',
    accent: 'blue',
    iconKey: 'building',
    logo: 'assets/empresa total.png',
    headerSub: 'Consolidado de todas las unidades operativas',
    tags: ['~1.842 empleados', '137 siniestros YTD'],
  },
  {
    id: 'sabores',
    group: 'UNIDADES',
    name: 'Sabores Express',
    sub: 'Cadena de locales gastronómicos',
    accent: 'blue',
    iconKey: 'utensils',
    logo: 'assets/sabores.png',
    headerSub: 'Cadena de locales gastronómicos · Abr 2026',
    tags: ['Locales Sabores', '53 siniestros YTD'],
  },
  {
    id: 'extremas',
    group: 'UNIDADES',
    name: 'Extremas',
    sub: 'Operación logística y distribución',
    accent: 'cyan',
    iconKey: 'truck',
    logo: 'assets/extremas.png',
    headerSub: 'Operación logística y distribución · Abr 2026',
    tags: ['Locales Extremas', 'Ausentismo 4.38%'],
  },
  {
    id: 'staff',
    group: 'UNIDADES',
    name: 'Staff',
    sub: 'Áreas corporativas y administración',
    accent: 'purple',
    iconKey: 'briefcase',
    logo: 'assets/Staff.png',
    headerSub: 'Áreas corporativas y administración · Abr 2026',
    tags: ['Personal Staff', '9 siniestros YTD'],
  },
  {
    id: 'fabrica',
    group: 'UNIDADES',
    name: 'Fábrica',
    sub: 'Plantas productivas',
    accent: 'amber',
    iconKey: 'factory',
    logo: 'assets/fabrica.png',
    headerSub: 'Plantas productivas · Abr 2026',
    tags: ['74 siniestros YTD', '1.258 días caídos'],
  },
  {
    id: 'judiciales',
    group: 'GESTIÓN',
    name: 'Inf. Judiciales',
    sub: 'Acuerdos y resoluciones por razón social',
    accent: 'purple',
    iconKey: 'gavel',
    logo: 'assets/informes judiciales.png',
    headerSub: 'Acuerdos y resoluciones · Mayo 2026',
    tags: ['38 acuerdos', '$194.9M'],
  },
  {
    id: 'inspecciones',
    group: 'GESTIÓN',
    name: 'Inspecciones',
    sub: 'Visitas, observaciones y cumplimiento',
    accent: 'green',
    iconKey: 'search',
    logo: 'assets/inspecciones.png',
    headerSub: 'Visitas regulatorias y de cumplimiento · Mayo 2026',
    tags: ['20 inspecciones', '5 multas'],
  },
  {
    id: 'horasextras',
    group: 'GESTIÓN',
    name: 'Horas Extras',
    sub: 'Horas, costo y distribución por unidad',
    accent: 'amber',
    iconKey: 'clock',
    logo: 'assets/horas extras.png',
    headerSub: 'Horas extras, costo y distribución · Abr 2026',
    tags: ['4.169 hs', '$49.2M'],
  },
  {
    id: 'accidentabilidad',
    group: 'GESTIÓN',
    name: 'Accidentabilidad',
    sub: 'Tasa, días caídos y reporte de siniestros',
    accent: 'red',
    iconKey: 'alert',
    logo: 'assets/accidentabilidad.png',
    headerSub: 'Tasa, días caídos y reporte de siniestros · YTD 2026',
    tags: ['137 siniestros YTD', '2.197 días caídos'],
  },
];

window.SECTOR_DATA = {
  empresa: {
    kpis: [
      { label: 'Ausentismo', value: '5.99%', delta: { dir: 'up', text: 'Abr 2026 · base 101.574 días' } },
      { label: 'Rotación YTD', value: '91.2%', delta: { dir: 'up', text: 'Feb 2026 · 402 altas / 337 bajas' } },
      { label: 'Siniestros YTD', value: '137', delta: { dir: 'neutral', text: '2.197 días caídos totales' } },
    ],
    charts: [
      {
        type: 'bar',
        title: 'Ausentismo por unidad — Abr 2026',
        sub: '% sobre base de días',
        data: [
          {x:'Staff',y:9.28},
          {x:'Fábricas',y:11.43},
          {x:'Extremas',y:4.38},
          {x:'Sabores',y:3.56},
        ],
      },
      {
        type: 'line',
        title: 'Ausentismo total empresa',
        sub: '% Ene–Abr 2026',
        data: [{x:'Ene',y:4.26},{x:'Feb',y:4.33},{x:'Mar',y:6.03},{x:'Abr',y:5.99}],
      },
      {
        type: 'bar',
        title: 'Altas y Bajas',
        sub: 'Ene–Abr 2026',
        data: [{x:'Ene',y:472},{x:'Feb',y:402},{x:'Mar',y:437},{x:'Abr',y:182}],
      },
      {
        type: 'line',
        title: 'Bajas por mes',
        sub: 'Ene–Abr 2026',
        data: [{x:'Ene',y:381},{x:'Feb',y:337},{x:'Mar',y:311},{x:'Abr',y:153}],
      },
    ],
  },

  sabores: {
    kpis: [
      { label: 'Ausentismo Locales Sabores', value: '3.56%', delta: { dir: 'down', text: 'Abr 2026 · base 43.532 días' } },
      { label: 'Siniestros YTD (Locales)', value: '53', delta: { dir: 'neutral', text: 'Fuente: tabla dinámica YTD' } },
      { label: 'Ausencias injustificadas', value: '304', delta: { dir: 'up', text: 'Abr 2026 · locales sabores' } },
    ],
    charts: [
      {
        type: 'line',
        title: 'Ausentismo Locales Sabores',
        sub: '% Ene–Abr 2026',
        data: [{x:'Ene',y:4.74},{x:'Feb',y:4.16},{x:'Mar',y:5.17},{x:'Abr',y:3.56}],
      },
      {
        type: 'bar',
        title: 'Días ausentismo Sabores por causa — Abr',
        sub: 'Días',
        data: [
          {x:'Aus. Injust.',y:304},
          {x:'Suspensión',y:159},
          {x:'Lic. Enf.',y:387},
          {x:'ART',y:45},
          {x:'Vacaciones',y:621},
          {x:'Maternidad',y:8},
        ],
      },
      {
        type: 'bar',
        title: 'Siniestros Locales por tipo de ocurrencia YTD',
        sub: 'Cantidad',
        data: [{x:'In Itinere',y:17},{x:'Laboral',y:35},{x:'Laboral*',y:1}],
      },
      {
        type: 'bar',
        title: 'Retención temprana — 1° Mes, 1° Quincena, 1° Día',
        sub: 'Bajas prematuras promedio YTD',
        data: [{x:'1° Mes',y:41.6},{x:'1° Quincena',y:32.5},{x:'1° Día',y:15.9}],
      },
    ],
  },

  extremas: {
    kpis: [
      { label: 'Ausentismo Locales Extremas', value: '4.38%', delta: { dir: 'up', text: 'Abr 2026 · base 27.144 días' } },
      { label: 'Ausencias injustificadas', value: '294', delta: { dir: 'up', text: 'Abr 2026' } },
      { label: 'Hs extras Extremas — Abr', value: '415 hs', delta: { dir: 'down', text: '$5.044.575 liquidados' } },
    ],
    charts: [
      {
        type: 'line',
        title: 'Ausentismo Locales Extremas',
        sub: '% Ene–Abr 2026',
        data: [{x:'Ene',y:1.4},{x:'Feb',y:1.29},{x:'Mar',y:7.17},{x:'Abr',y:4.38}],
      },
      {
        type: 'bar',
        title: 'Días ausentismo Extremas por causa — Abr',
        sub: 'Días',
        data: [
          {x:'Aus. Injust.',y:294},
          {x:'Suspensión',y:148},
          {x:'Lic. Enf.',y:344},
          {x:'ART',y:100},
          {x:'Vacaciones',y:147},
        ],
      },
      {
        type: 'line',
        title: 'Horas extras Extremas por mes',
        sub: 'Cantidad de horas',
        data: [{x:'Ene',y:796},{x:'Feb',y:611},{x:'Mar',y:379},{x:'Abr',y:415}],
      },
      {
        type: 'bar',
        title: 'Siniestros Locales — tipo de ocurrencia YTD',
        sub: 'Cantidad',
        data: [{x:'In Itinere',y:17},{x:'Laboral',y:35},{x:'Laboral*',y:1}],
      },
    ],
  },

  staff: {
    kpis: [
      { label: 'Ausentismo Staff', value: '9.28%', delta: { dir: 'up', text: 'Abr 2026 · incluye maternidad' } },
      { label: 'Siniestros Mant/Staff YTD', value: '9', delta: { dir: 'neutral', text: '6 in itinere · 3 laboral' } },
      { label: 'Ausencias injustificadas', value: '26', delta: { dir: 'neutral', text: 'Feb 2026' } },
    ],
    charts: [
      {
        type: 'bar',
        title: 'Ausentismo Staff por causa — Feb 2026',
        sub: 'Días',
        data: [
          {x:'Aus. Injust.',y:26},
          {x:'Suspensión',y:18},
          {x:'Lic. Enf.',y:42},
          {x:'ART',y:27},
          {x:'Vacaciones',y:407},
          {x:'Sancor',y:52},
        ],
      },
      {
        type: 'bar',
        title: 'Siniestros Mantenimiento/Staff YTD',
        sub: 'Por tipo de ocurrencia',
        data: [{x:'In Itinere',y:6},{x:'Laboral',y:2},{x:'Laboral*',y:1}],
      },
      {
        type: 'bar',
        title: 'Gravedad — Mant/Staff YTD',
        sub: 'Cantidad',
        data: [{x:'Leve',y:8},{x:'Moderado',y:1}],
      },
      {
        type: 'bar',
        title: 'Bajas prematuras promedio YTD',
        sub: 'Retención temprana',
        data: [{x:'1° Mes',y:41.6},{x:'1° Quincena',y:32.5},{x:'1° Día',y:15.9}],
      },
    ],
  },

  fabrica: {
    kpis: [
      { label: 'Ausentismo Fábricas', value: '11.43%', delta: { dir: 'up', text: 'Abr 2026 · base días fábricas' } },
      { label: 'Siniestros Fábrica YTD', value: '74', delta: { dir: 'up', text: '1.258 días caídos' } },
      { label: 'Hs extras Logística — Abr', value: '2.364 hs', delta: { dir: 'down', text: '$28.7M liquidados' } },
    ],
    charts: [
      {
        type: 'line',
        title: 'Ausentismo Fábricas',
        sub: '% Ene–Abr 2026',
        data: [{x:'Ene',y:8.6},{x:'Feb',y:6.67},{x:'Mar',y:9.21},{x:'Abr',y:11.43}],
      },
      {
        type: 'bar',
        title: 'Siniestros Fábrica — tendencia mensual YTD',
        sub: 'Cantidad',
        data: [{x:'Ene',y:3},{x:'Feb',y:5},{x:'Mar',y:6},{x:'Abr',y:3},{x:'May',y:3},{x:'Jun',y:11},{x:'Jul',y:10},{x:'Ago',y:15},{x:'Sep',y:10},{x:'Oct',y:8}],
      },
      {
        type: 'bar',
        title: 'Siniestros Fábrica — por planta YTD',
        sub: 'Cantidad',
        data: [
          {x:'San Martín',y:23},
          {x:'San Miguel',y:34},
          {x:'JYQ',y:3},
          {x:'Medialunas',y:2},
          {x:'Tapas 1',y:4},
          {x:'Pizzas',y:2},
          {x:'Procesadora',y:1},
          {x:'Congelados',y:1},
          {x:'Tapas 2',y:1},
          {x:'JYQ*',y:3},
        ],
      },
      {
        type: 'bar',
        title: 'Horas extras por sector — Abr 2026',
        sub: 'Horas',
        data: [
          {x:'Logística',y:2364},
          {x:'JYQ',y:555},
          {x:'Extremas',y:415},
          {x:'Medialunas',y:395},
          {x:'San Miguel',y:327},
          {x:'Panificado',y:53},
          {x:'Proce.',y:60},
        ],
      },
    ],
  },

  judiciales: {
    kpis: [
      { label: 'Total acuerdos — Mayo 2026', value: '$194.9M', delta: { dir: 'up', text: '38 acuerdos' } },
      { label: 'Total acuerdos — Mayo 2025', value: '$57.4M', delta: { dir: 'neutral', text: '21 acuerdos' } },
      { label: 'Variación interanual', value: '+239.5%', delta: { dir: 'up', text: '$57.4M → $194.9M' }, valueClass: 'is-down' },
    ],
    charts: [
      {
        type: 'hbar',
        title: 'Monto por razón social — Mayo 2026',
        sub: 'Millones $',
        data: [
          {x:'CHUSPITA MARTIN',y:46.79},
          {x:'BOLLOS Y RELLENOS',y:12.99},
          {x:'LA EMPANADERIA',y:29.76},
          {x:'CASTRO CINTIA',y:11.13},
          {x:'GONZALEZ MIGUEL',y:14.13},
          {x:'IVO PISANIELLO',y:12.93},
          {x:'RUANO ROJAS',y:9.93},
          {x:'VICTORICA B.',y:3.27},
          {x:'VICTORICA A.',y:4.93},
          {x:'VILLA MARIANO',y:11.37},
          {x:'BRUNO RIOS',y:11.45},
          {x:'SORIA ADRIAN',y:2.60},
          {x:'SAYAGO MARCIO',y:7.20},
          {x:'COMACHI V.',y:7.33},
          {x:'CERTALDO',y:3.76},
          {x:'TABEIRA',y:4.48},
          {x:'MOSCARELLA',y:1.86},
        ],
      },
      {
        type: 'donut',
        title: 'Distribución por tipo (monto)',
        sub: '% del total Mayo 2026',
        data: [
          { label:'Locales', value: 82 },
          { label:'Fábrica', value: 18 },
          { label:'Staff',   value: 0  },
        ],
      },
    ],
    details: [
      {
        key: 'detalle-acuerdos',
        title: 'Detalle acuerdos — Mayo 2026',
        iconEmoji: '⚖️',
        accent: 'purple',
        type: 'table',
        topChips: [
          { label:'Fábrica',  value:'18%', tone:'blue' },
          { label:'Locales',  value:'82%', tone:'green' },
          { label:'Staff',    value:'0%',  tone:'purple' },
        ],
        columns: [
          { key:'razon',  label:'RAZÓN SOCIAL' },
          { key:'unidad', label:'LOCAL / FÁBRICA' },
          { key:'tipo',   label:'TIPO', badge:true },
          { key:'actor',  label:'ACTOR', align:'right' },
          { key:'total',  label:'TOTAL', align:'right', strong:true },
        ],
        rows: [
          { razon:'CHUSPITA MARTIN DANIEL',   unidad:'SABORES MDQ 3',          tipo:'Sabores',  actor:'$22.500.000', total:'$38.054.500' },
          { razon:'CHUSPITA MARTIN DANIEL',   unidad:'SABORES MDQ 4',          tipo:'Sabores',  actor:'$7.000.000',  total:'$8.732.500' },
          { razon:'LA EMPANADERIA',           unidad:'FABRICA SAN MARTIN',     tipo:'Fábrica',  actor:'$18.000.000', total:'$21.733.000' },
          { razon:'LA EMPANADERIA',           unidad:'FABRICA SAN MARTIN',     tipo:'Fábrica',  actor:'$3.200.000',  total:'$4.293.650' },
          { razon:'LA EMPANADERIA',           unidad:'FABRICA SAN MARTIN',     tipo:'Fábrica',  actor:'$3.000.000',  total:'$3.731.670' },
          { razon:'BOLLOS Y RELLENOS',        unidad:'FABRICA SAN MIGUEL',     tipo:'Fábrica',  actor:'$6.000.000',  total:'$7.331.670' },
          { razon:'GONZALEZ MIGUEL ANGEL',    unidad:'EXTREMAS MUNRO',         tipo:'Extremas', actor:'$3.500.000',  total:'$4.333.650' },
          { razon:'GONZALEZ MIGUEL ANGEL',    unidad:'SABORES DEL VISO',       tipo:'Sabores',  actor:'$3.500.000',  total:'$4.333.650' },
          { razon:'BRUNO RIOS',               unidad:'SABORES HURLINGHAM II',  tipo:'Sabores',  actor:'$4.000.000',  total:'$4.961.720' },
          { razon:'VICTORICA ANA MACARENA',   unidad:'SABORES BERAZATEGUI II', tipo:'Sabores',  actor:'$4.000.000',  total:'$4.931.670' },
        ],
      },
    ],
  },

  inspecciones: {
    kpis: [
      { label: 'Inspecciones — Mayo 2026', value: '20',   delta: { dir: 'neutral', text: '18 audiencias programadas' } },
      { label: 'Multas aplicadas',          value: '5',    delta: { dir: 'up',      text: 'Monto total $15.4M' } },
      { label: 'Demandas',                  value: '1',    delta: { dir: 'neutral', text: '$1.1M — La Empanadería' } },
    ],
    charts: [
      {
        type: 'bar',
        title: 'Inspecciones por unipersonal — Mayo 2026',
        sub: 'Cantidad',
        data: [
          {x:'PISANIELLO',y:3},
          {x:'RUANO ROJAS',y:3},
          {x:'BAJOS DE PARLA',y:3},
          {x:'CASTRO CINTIA',y:2},
          {x:'GONZALEZ M.',y:2},
          {x:'CHUSPITA',y:2},
          {x:'CASUT FRIJON',y:1},
          {x:'SORIA ADRIAN',y:1},
          {x:'TABEIRA',y:1},
          {x:'RIOS BRUNO',y:1},
          {x:'SAYAGO MARCIO',y:1},
        ],
      },
      {
        type: 'donut',
        title: 'Montos multas por unipersonal',
        sub: 'Mayo 2026',
        data: [
          { label:'Bollos y Rellenos', value: 8192070 },
          { label:'Casut Frijon',      value: 3000000 },
          { label:'Sayago Leandro',    value: 2407235 },
          { label:'Victorica Barbara', value: 1842443 },
        ],
      },
    ],
    details: [
      {
        key: 'multas-mayo',
        title: 'Multas aplicadas — Mayo 2026',
        iconEmoji: '🔍',
        accent: 'red',
        type: 'table',
        columns: [
          { key:'razon',  label:'RAZÓN SOCIAL' },
          { key:'local',  label:'LOCAL' },
          { key:'multas', label:'MULTAS', align:'right' },
          { key:'monto',  label:'MONTO',  align:'right', strong:true },
        ],
        rows: [
          { razon:'VICTORICA BARBARA ALEJANDRA',  local:'—',                          multas:1, monto:'$1.842.443' },
          { razon:'SAYAGO LEANDRO MIGUEL AGUSTIN', local:'SE - Cruce Castelar',        multas:1, monto:'$2.407.235' },
          { razon:'CASUT FRIJON MATIAS EZEQUIEL',  local:'—',                          multas:1, monto:'$3.000.000' },
          { razon:'BOLLOS Y RELLENOS',             local:'Oficina 228 Paralelo',        multas:2, monto:'$8.192.070' },
        ],
        totalRow: { label:'TOTAL', value:'$15.441.748', extra:'5' },
      },
      {
        key: 'audiencias-mayo',
        title: 'Audiencias programadas — Mayo 2026',
        iconEmoji: '📋',
        accent: 'blue',
        type: 'table',
        columns: [
          { key:'razon',   label:'RAZÓN SOCIAL' },
          { key:'local',   label:'LOCAL' },
          { key:'motivo',  label:'MOTIVO' },
          { key:'estado',  label:'ESTADO', badge:'good' },
        ],
        rows: [
          { razon:'CASTRO CINTIA',     local:'Extremas Flores 2',    motivo:'Acta de comprobación',       estado:'Entregada' },
          { razon:'CASTRO CINTIA',     local:'Extremas Caseros',     motivo:'Acta de comprobación',       estado:'Entregada' },
          { razon:'CASUT MATIAS',      local:'Extremas Pacheco',     motivo:'Acta de comprobación',       estado:'Entregada' },
          { razon:'CHUSPITA MARTIN',   local:'Sabores MDQ 1',        motivo:'Acta de comprobación',       estado:'Entregada' },
          { razon:'PISANIELLO IVO',    local:'Sabores El Palomar',   motivo:'Relevamiento pers. altas/bajas', estado:'Entregada' },
          { razon:'RUANO GREISSI',     local:'Extremas San Justo',   motivo:'Relevamiento pers. altas/bajas', estado:'Entregada' },
          { razon:'GONZALEZ MIGUEL',   local:'Extremas Munro',       motivo:'Relevamiento pers. altas/bajas', estado:'Entregada' },
          { razon:'VILLA MARIANO',     local:'Sabores Polvorines',   motivo:'Acta de comprobación',       estado:'Entregada' },
        ],
      },
    ],
  },

  horasextras: {
    kpis: [
      { label: 'Horas extras — Abr 2026', value: '4.169 hs', delta: { dir: 'up', text: '+10.3% vs Mar 2026' } },
      { label: 'Costo liquidado — Abr',   value: '$49.2M',   delta: { dir: 'up', text: '+27% vs Mar 2026' } },
      { label: 'Mayor carga — Logística', value: '2.364 hs', delta: { dir: 'neutral', text: '$28.7M Logística Abr' } },
    ],
    charts: [
      {
        type: 'line',
        title: 'Evolución horas extras totales',
        sub: 'Ene–Abr 2026',
        data: [{x:'Ene',y:6325},{x:'Feb',y:4479},{x:'Mar',y:3779},{x:'Abr',y:4169}],
      },
      {
        type: 'line',
        title: 'Evolución costo horas extras',
        sub: 'Millones $ · Ene–Abr 2026',
        data: [{x:'Ene',y:67.3},{x:'Feb',y:49.4},{x:'Mar',y:38.8},{x:'Abr',y:49.2}],
      },
      {
        type: 'bar',
        title: 'Horas extras por sector — Abr 2026',
        sub: 'Horas liquidadas',
        data: [
          {x:'Logística',y:2364},
          {x:'Extremas',y:415},
          {x:'JYQ',y:555},
          {x:'Medialunas',y:395},
          {x:'San Miguel',y:327},
          {x:'Panificado',y:53},
          {x:'Procesadora',y:60},
        ],
      },
      {
        type: 'bar',
        title: 'Costo por sector — Abr 2026',
        sub: 'Millones $',
        data: [
          {x:'Logística',y:28.7},
          {x:'JYQ',y:6.2},
          {x:'Extremas',y:5.0},
          {x:'Medialunas',y:4.7},
          {x:'San Miguel',y:3.4},
          {x:'Panificado',y:0.55},
          {x:'Procesadora',y:0.55},
        ],
      },
    ],
    details: [
      {
        key: 'detalle-he',
        title: 'Detalle horas extras por sector — Abr 2026',
        iconEmoji: '⏱️',
        accent: 'amber',
        type: 'table',
        columns: [
          { key:'sector', label:'SECTOR' },
          { key:'horas',  label:'HORAS', align:'right' },
          { key:'costo',  label:'COSTO', align:'right', strong:true },
        ],
        rows: [
          { sector:'LOGÍSTICA',    horas:'2.364', costo:'$28.732.277' },
          { sector:'JYQ',          horas:'555',   costo:'$6.230.273' },
          { sector:'EXTREMAS',     horas:'415',   costo:'$5.044.575' },
          { sector:'MEDIALUNAS',   horas:'395',   costo:'$4.696.939' },
          { sector:'SAN MIGUEL',   horas:'327',   costo:'$3.376.571' },
          { sector:'PROCESADORA',  horas:'60',    costo:'$551.665' },
          { sector:'PANIFICADO',   horas:'53',    costo:'$546.715' },
        ],
        totalRow: { label:'TOTAL ABR', value:'$49.179.015' },
      },
    ],
  },

  accidentabilidad: {
    kpis: [
      { label: 'Siniestros totales YTD',    value: '137',    delta: { dir: 'neutral', text: 'Todos los sectores' } },
      { label: 'Días caídos totales YTD',   value: '2.197',  delta: { dir: 'up',      text: 'Promedio 16 días/caso' } },
      { label: 'Índice siniestralidad',     value: '2.60%',  delta: { dir: 'neutral', text: 'Dotación base ~3.516' } },
    ],
    charts: [
      {
        type: 'bar',
        title: 'Siniestros por sector YTD',
        sub: 'Cantidad',
        data: [
          {x:'Fábrica',y:74},
          {x:'Locales',y:53},
          {x:'Mant/Staff',y:9},
          {x:'Fábrica*',y:1},
        ],
      },
      {
        type: 'donut',
        title: 'Tipo de ocurrencia YTD',
        sub: '% del total',
        data: [
          { label:'Laboral',     value: 90 },
          { label:'In Itinere',  value: 34 },
          { label:'Laboral*',    value: 13 },
        ],
      },
    ],
    details: [
      {
        key: 'reporte-siniestros',
        title: 'Siniestros activos en tratamiento',
        iconEmoji: '🛎️',
        accent: 'red',
        type: 'siniestros-report',
        groups: [
          {
            person: 'LEDESMA DEMIAN NAHUEL YAIR',
            local: 'LOCAL SAN MIGUEL EXTREMAS',
            tag: 'ART',
            rows: [
              { medida: 'Medidas Técnicas',     responsable: 'HYS',                      fecha: '19/08/26' },
              { medida: 'Medidas Organizativas',responsable: 'RRHH – OPERACIONES – HYS', fecha: '30/06/26' },
              { medida: 'Medidas Formativas',   responsable: 'HYS - OPERACIONES',        fecha: '19/08/26' },
            ],
          },
          {
            person: 'JADE ARIANA RAMIREZ HUAMAN',
            local: 'LOCAL PACHECO EXTREMAS',
            tag: 'SS',
            rows: [
              { medida: 'Medidas Técnicas',     responsable: 'HYS',                      fecha: '28/08/26' },
              { medida: 'Medidas Organizativas',responsable: 'RRHH – OPERACIONES – HYS', fecha: '30/06/26' },
              { medida: 'Medidas Formativas',   responsable: 'HYS - OPERACIONES',        fecha: '28/08/26' },
            ],
          },
          {
            person: 'LUZ MAITENA GOMEZ',
            local: 'LOCAL LAFERRERE SABORES',
            tag: 'SS',
            rows: [
              { medida: 'Medidas Técnicas',     responsable: 'Mantenimiento / Operaciones', fecha: '01/06/26' },
              { medida: 'Medidas Organizativas',responsable: 'Op. / HYS / Mantenimiento',   fecha: '01/06/26' },
              { medida: 'Medidas Formativas',   responsable: 'HYS',                          fecha: '12/05/26' },
            ],
          },
        ],
      },
    ],
  },
};
